#!/bin/bash
#
# Put me here: /bin/lock
# chmod +x /bin/lock
# Call me with lock
scrot /tmp/screenshot.png
convert /tmp/screenshot.png -blur 0x5 /tmp/screenshotblur.png
i3lock -i /tmp/screenshotblur.png
